services:
  statsd-exporter:
    image: prom/statsd-exporter:v0.28.0
    command:
      - "--statsd.listen-udp=:8125"
      - "--web.listen-address=:9102"
      # - "--statsd.mapping-config=/statsd-mapping.conf"
      - "--log.level=debug"
    ports:
      - "8125:8125/udp"
      - "9102:9102"
    # volumes:
    #   - "./statsd-mapping.conf:/statsd-mapping.conf"