global:
  scrape_interval: 30s
  scrape_timeout: 30s
  evaluation_interval: 30s

rule_files:

scrape_configs:
  - job_name: airflow
    static_configs:
      - targets:
        - host.docker.internal:9102
